#!/usr/bin/env python3
"""Emit the architectural invariants as data, read from the live code.

Every structural number Genesis publishes about itself - engine count, gate
count, fan-out ceilings, cycle count - appears in at least three places: the
README, the architecture reference, and the landing page. Prose copies of a
number drift silently; there is no compiler for a sentence.

This is the single source. It reads the running package rather than a
hand-maintained table, writes ARCHITECTURE_INVARIANTS.json, and a test asserts
the committed file still matches what the code reports. A structural change
that nobody documented turns that test red.

It also gives an agent - an MCP server, a code-review bot, a coding assistant
reading this repository - one unambiguous file to parse instead of inferring
architecture from prose.

    python scripts/architecture_invariants.py            # print
    python scripts/architecture_invariants.py --write    # regenerate the file
    python scripts/architecture_invariants.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = REPO / "ARCHITECTURE_INVARIANTS.json"


def collect() -> dict:
    """Read every published invariant out of the live package."""
    sys.path.insert(0, str(REPO / "src"))

    import genesis_architect
    from genesis_architect.core.antipattern_detector import (
        GOD_CLASS_FAN_OUT,
        HUB_FILE_FAN_IN,
    )
    from genesis_architect.core.import_graph import build_graph
    from genesis_architect.pro.engine_bootstrap import ensure_registered
    from genesis_architect.pro.engine_registry import get_default_registry
    from genesis_architect.pro.gde_gate_engine import _GATE_POLICY
    from genesis_architect.pro.gde_types import GDEMode

    ensure_registered()
    registry = get_default_registry()
    graph = build_graph(str(REPO))
    sources = json.loads(
        (REPO / "src/genesis_architect/pro/data/research_sources.json")
        .read_text(encoding="utf-8"))

    engines = sorted(d.id for d in registry.all())
    modules = graph["modules"]

    def fan_out(path: str) -> int:
        return modules.get(path, {}).get("fan_out", 0)

    cli = sorted(
        (p.stem, fan_out(f"src/genesis_architect/pro/commands/{p.name}"))
        for p in (REPO / "src/genesis_architect/pro/commands").glob("*.py")
        if p.stem != "__init__"
    )

    return {
        "_comment": (
            "Generated by scripts/architecture_invariants.py from the live "
            "package. Do not edit by hand - regenerate with --write. This is "
            "the source of truth for every structural number published about "
            "Genesis; prose that disagrees with this file is wrong."
        ),
        "version": genesis_architect.__version__,
        "python_requires": ">=3.11",
        "license": "AGPL-3.0-or-later",
        "counts": {
            "engines": len(engines),
            "gates": len(_GATE_POLICY),
            "modes": len(list(GDEMode)),
            "research_sources": len(sources["sources"]),
            "research_tiers": len(sources["tiers"]),
        },
        # Only things that must hold regardless of how the repo grows.
        # Module and edge counts deliberately excluded: they move whenever any
        # file is added, including a test, which would make this file stale on
        # almost every commit and train people to regenerate without reading.
        "structure": {
            "import_cycles": graph["cycle_count"],
        },
        "thresholds": {
            "god_class_fan_out": GOD_CLASS_FAN_OUT,
            "god_class_critical_above": 30,
            "hub_file_fan_in": HUB_FILE_FAN_IN,
            "hub_file_critical_above": 20,
            "self_imposed_fan_out_ceiling": 11,
        },
        "invariants": [
            "import_cycles == 0",
            "every module in pro/commands has fan_out <= 11",
            "requires edges are acyclic; handoffs edges may cycle by design",
            "imports under `if TYPE_CHECKING:` are not dependency edges",
            "test files are excluded from hub-file fan-in",
            "a metric that was not measured is None, never 0",
        ],
        "engines": engines,
        "modes": [m.value for m in GDEMode],
        "gates": [
            {"id": g[0], "action": g[3].value, "overridable": g[2],
             "confidence_penalty": g[4]}
            for g in _GATE_POLICY
        ],
        "cli_modules": [{"module": n, "fan_out": f} for n, f in cli],
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true", help="regenerate the file")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file is stale")
    args = ap.parse_args()

    data = collect()
    rendered = json.dumps(data, indent=2) + "\n"

    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(REPO)}")
        return 0

    if args.check:
        if not OUTPUT.is_file():
            print(f"MISSING: {OUTPUT.name} - run with --write", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"STALE: {OUTPUT.name} disagrees with the live package.\n"
                  f"       Regenerate: python scripts/architecture_invariants.py --write",
                  file=sys.stderr)
            return 1
        print(f"{OUTPUT.name} matches the live package")
        return 0

    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
