#!/usr/bin/env python3
"""
drift_detector.py - Detect architecture drift from initial ADR decisions.

Two levels of drift detection:

  LEVEL 1 - Structural drift (original):
    Compares current directory tree against docs/adr/001-initial-architecture.md.
    Catches: new unexpected directories, missing expected directories.
    The 10x growth heuristic is REMOVED - it was measuring the wrong thing.

  LEVEL 2 - Import boundary drift (new in v2.6.0):
    Reads architecture rules from .genesis/evidence.json (generated by evidence_pack.py).
    Walks all Python source files and checks:
      - forbidden_imports: modules that must NOT be imported (e.g. sqlite3 when ADR says "no database")
      - required_imports: modules that MUST be imported in specific files (e.g. logging in entry points)
    Uses AST analysis - no exec, no subprocess.

Usage:
  python scripts/drift_detector.py [project_path]
  python scripts/drift_detector.py [project_path] --level 2
  python scripts/drift_detector.py [project_path] --json
"""

import ast
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


ADR_PATH = "docs/adr/001-initial-architecture.md"
SRC_DIR = "src"

# Directories never flagged as "unexpected" - standard tooling output
_IGNORED_DIRS = frozenset({
    "node_modules", "venv", ".venv", "dist", "build",
    ".genesis", "__pycache__", ".pytest_cache", ".ruff_cache",
    "htmlcov", ".mypy_cache",
})


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class ImportViolation:
    file: str
    line: int
    module: str
    rule: str  # "forbidden" or "required_missing"
    detail: str


@dataclass
class DriftReport:
    new_dirs: list[str] = field(default_factory=list)
    missing_dirs: list[str] = field(default_factory=list)
    import_violations: list[ImportViolation] = field(default_factory=list)
    adr_found: bool = False
    evidence_found: bool = False

    @property
    def has_structural_drift(self) -> bool:
        return bool(self.new_dirs or self.missing_dirs)

    @property
    def has_import_violations(self) -> bool:
        return bool(self.import_violations)

    @property
    def ok(self) -> bool:
        return not self.has_structural_drift and not self.has_import_violations


# ---------------------------------------------------------------------------
# Level 1: structural drift
# ---------------------------------------------------------------------------

def _safe_path(base: Path, target: Path) -> Path:
    if not target.resolve().is_relative_to(base.resolve()):
        raise PermissionError(f"Path outside project: {target}")
    return target


def _parse_code_block_dirs(lines: list[str]) -> list[str]:
    dirs = []
    in_block = False
    for line in lines:
        if "```" in line:
            in_block = not in_block
            continue
        if in_block:
            match = re.match(r"^[├└│\s]+(\w[\w.-]*)/", line)
            if match:
                dirs.append(match.group(1))
    return dirs


def _parse_bullet_dirs(lines: list[str]) -> list[str]:
    dirs = []
    for line in lines:
        match = re.match(r"^\s*[-*]\s+`?([a-z][a-z0-9_-]+)/`?", line)
        if match:
            dirs.append(match.group(1))
    return dirs


def _parse_adr_structure(adr_content: str) -> list[str]:
    lines = adr_content.splitlines()
    dirs = _parse_code_block_dirs(lines) + _parse_bullet_dirs(lines)
    return list(set(dirs)) if dirs else ["src", "tests", "docs"]


def _detect_structural_drift(root: Path) -> tuple[list[str], list[str], bool]:
    """Return (new_dirs, missing_dirs, adr_found)."""
    adr_file = root / ADR_PATH
    adr_found = adr_file.exists()

    if adr_found:
        try:
            _safe_path(root, adr_file)
            content = adr_file.read_text(encoding="utf-8")
            expected_dirs = _parse_adr_structure(content)
        except Exception:
            expected_dirs = ["src", "tests", "docs"]
    else:
        expected_dirs = ["src", "tests", "docs"]

    top_level_actual = [
        d.name for d in root.iterdir()
        if d.is_dir() and not d.name.startswith(".") and d.name not in _IGNORED_DIRS
    ]

    new_dirs = [d for d in top_level_actual if d not in expected_dirs]
    missing_dirs = [d for d in expected_dirs if d not in top_level_actual]
    return new_dirs, missing_dirs, adr_found


# ---------------------------------------------------------------------------
# Level 2: import boundary drift (AST-based)
# ---------------------------------------------------------------------------

def _load_architecture_rules(root: Path) -> dict:
    """
    Load import boundary rules from .genesis/evidence.json.

    The evidence JSON stores arch_rationale as free text. We extract
    structured rules from an optional 'architecture_rules' key (added
    in v2.6.0) OR derive conservative defaults from the arch_rationale
    text by looking for known forbidden-pattern phrases.

    Returns a dict with:
        forbidden_imports: list[str]   - module names that must never appear
        required_in_files: list[dict]  - [{file_glob, import_name}]
    """
    evidence_path = root / ".genesis" / "evidence.json"
    if not evidence_path.exists():
        return {}

    try:
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}

    # Explicit rules take priority (set by genesis validate --add-rule in future)
    if "architecture_rules" in evidence:
        return evidence["architecture_rules"]

    # Derive conservative rules from arch_rationale prose
    rules: dict = {"forbidden_imports": [], "required_in_files": []}
    rationale = evidence.get("arch_rationale", "").lower()

    # "no database" -> forbid sqlite3, sqlalchemy, psycopg2, pymongo
    if any(phrase in rationale for phrase in ("no database", "no db", "file-based state", "json state")):
        rules["forbidden_imports"].extend(["sqlite3", "sqlalchemy", "psycopg2", "pymongo", "motor"])

    # "no server" (CLI archetype) -> forbid flask, fastapi, starlette, django
    archetype = evidence.get("archetype", "").lower()
    if archetype == "cli" or "no server" in rationale:
        rules["forbidden_imports"].extend(["flask", "fastapi", "starlette", "django", "aiohttp"])

    # "requests-first" -> forbid urllib as primary HTTP (only flag if also feedparser is allowed)
    # This is nuanced - skip this auto-derivation to avoid false positives.

    # Dedup
    rules["forbidden_imports"] = list(set(rules["forbidden_imports"]))
    return rules


def _collect_python_files(src_root: Path) -> list[Path]:
    """Return all .py files under src_root, excluding __pycache__."""
    if not src_root.exists():
        return []
    return [
        p for p in src_root.rglob("*.py")
        if "__pycache__" not in p.parts
    ]


def _get_imports_from_file(py_file: Path) -> list[tuple[int, str]]:
    """
    Return list of (lineno, top_level_module_name) for every import in the file.
    Uses AST - no exec.
    """
    try:
        source = py_file.read_text(encoding="utf-8", errors="replace")
        tree = ast.parse(source)
    except (OSError, SyntaxError):
        return []

    imports: list[tuple[int, str]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                top = alias.name.split(".")[0]
                imports.append((node.lineno, top))
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                top = node.module.split(".")[0]
                imports.append((node.lineno, top))
    return imports


def _check_import_boundaries(
    root: Path,
    rules: dict,
) -> list[ImportViolation]:
    """
    Walk all Python source files and check imports against architecture rules.
    Returns list of ImportViolation objects.
    """
    violations: list[ImportViolation] = []
    forbidden: set[str] = set(rules.get("forbidden_imports", []))
    if not forbidden:
        return violations

    src_root = root / SRC_DIR
    py_files = _collect_python_files(src_root)
    # Also check project root-level scripts
    py_files += [p for p in root.glob("*.py") if "__pycache__" not in p.parts]

    for py_file in py_files:
        rel = py_file.relative_to(root)
        for lineno, module in _get_imports_from_file(py_file):
            if module in forbidden:
                violations.append(ImportViolation(
                    file=str(rel),
                    line=lineno,
                    module=module,
                    rule="forbidden",
                    detail=(
                        f"Import of '{module}' violates architecture rule "
                        f"(derived from ADR: forbidden_imports). "
                        f"If this import is intentional, update .genesis/evidence.json "
                        f"architecture_rules.forbidden_imports to remove '{module}'."
                    ),
                ))

    return violations


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def detect_drift(project_path: str = ".", level: int = 2) -> DriftReport:
    """
    Run drift detection at the requested level.

    level=1: structural drift only (directories vs ADR)
    level=2: structural + import boundary drift (default)
    """
    root = Path(project_path).resolve()
    report = DriftReport()

    # Level 1: structural
    new_dirs, missing_dirs, adr_found = _detect_structural_drift(root)
    report.new_dirs = new_dirs
    report.missing_dirs = missing_dirs
    report.adr_found = adr_found

    # Level 2: import boundary
    if level >= 2:
        rules = _load_architecture_rules(root)
        report.evidence_found = bool(rules)
        if rules:
            report.import_violations = _check_import_boundaries(root, rules)

    return report


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def print_report(report: DriftReport, project_path: str = ".") -> None:
    print("\nArchitecture Drift Report")
    print(f"Project: {Path(project_path).resolve()}")
    if not report.adr_found:
        print(f"  Note: {ADR_PATH} not found. Using defaults (src, tests, docs).")
    if not report.evidence_found:
        print("  Note: .genesis/evidence.json not found. Import boundary checks skipped.")
        print("        Run: python scripts/evidence_pack.py generate --project-dir .")
    print()

    if report.ok:
        print("  No drift detected.")
        return

    if report.new_dirs:
        print(f"  STRUCTURAL: Unexpected directories (not in ADR): {report.new_dirs}")
        print("  Action: add to ADR if intentional, or remove if accidental.")

    if report.missing_dirs:
        print(f"  STRUCTURAL: Missing directories (in ADR but absent): {report.missing_dirs}")
        print("  Action: create them or update ADR.")

    if report.import_violations:
        print(f"  IMPORT BOUNDARY: {len(report.import_violations)} violation(s):")
        for v in report.import_violations:
            print(f"    [{v.rule.upper()}] {v.file}:{v.line} imports '{v.module}'")
            print(f"      {v.detail}")


def print_json_report(report: DriftReport) -> None:
    output = {
        "ok": report.ok,
        "structural_drift": {
            "new_dirs": report.new_dirs,
            "missing_dirs": report.missing_dirs,
        },
        "import_violations": [
            {
                "file": v.file,
                "line": v.line,
                "module": v.module,
                "rule": v.rule,
                "detail": v.detail,
            }
            for v in report.import_violations
        ],
        "adr_found": report.adr_found,
        "evidence_found": report.evidence_found,
    }
    print(json.dumps(output, indent=2))


def main() -> None:
    if len(sys.argv) > 1 and sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    args = sys.argv[1:]
    project_path = "."
    level = 2
    as_json = False

    skip_next = False
    for i, arg in enumerate(args):
        if skip_next:
            skip_next = False
            continue
        if arg == "--json":
            as_json = True
        elif arg == "--level":
            try:
                level = int(args[i + 1])
                skip_next = True
            except (IndexError, ValueError):
                level = 2
        elif arg.startswith("--level="):
            try:
                level = int(arg.split("=")[1])
            except ValueError:
                level = 2
        elif not arg.startswith("--"):
            project_path = arg

    report = detect_drift(project_path, level=level)

    if as_json:
        print_json_report(report)
    else:
        print_report(report, project_path)

    sys.exit(1 if not report.ok else 0)


if __name__ == "__main__":
    main()
