#!/usr/bin/env python3
"""
research_validator.py - Genesis Architect
Validates that a generated RESEARCH.md is complete and well-formed.
Exits with code 0 if valid, code 1 if issues found.

Usage:
  python scripts/research_validator.py RESEARCH.md
  python scripts/research_validator.py path/to/project/RESEARCH.md
"""

import sys
import re

REQUIRED_SECTIONS = [
    "Executive Summary",
    "Search Scope",
    "Analyzed Repositories",
    "Market Landscape",
    "Architecture Decision Rationale",
    "Sources",
]

MIN_REPOS = 5
MIN_SOURCES = 3


def validate(path: str) -> list[str]:
    """Returns a list of issues. Empty list = valid."""
    issues = []

    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        return [f"File not found: {path}"]

    # Check required sections
    for section in REQUIRED_SECTIONS:
        if section not in content:
            issues.append(f"Missing section: '{section}'")

    # Check repo count in table
    table_rows = re.findall(r"^\|[^|]+\|[^|]+\|[^|]+\|[^|]+\|", content, re.MULTILINE)
    # Subtract header and separator rows
    data_rows = [r for r in table_rows if not re.match(r"^\|\s*[-:]+\s*\|", r)]
    if len(data_rows) < MIN_REPOS:
        issues.append(
            f"Too few repos in table: found {len(data_rows)}, minimum is {MIN_REPOS}"
        )

    # Check for at least MIN_SOURCES links
    links = re.findall(r"https?://\S+", content)
    if len(links) < MIN_SOURCES:
        issues.append(f"Too few source links: found {len(links)}, minimum is {MIN_SOURCES}")

    # Check it was generated by Genesis Architect
    if "Genesis Architect" not in content:
        issues.append("Missing 'Genesis Architect' header - was this generated by the skill?")

    return issues


def main():
    if len(sys.argv) < 2:
        print("Usage: python research_validator.py <path-to-RESEARCH.md>")
        sys.exit(1)

    path = sys.argv[1]
    issues = validate(path)

    if not issues:
        print(f"RESEARCH.md is valid.")
        sys.exit(0)
    else:
        print(f"RESEARCH.md has {len(issues)} issue(s):")
        for issue in issues:
            print(f"  - {issue}")
        sys.exit(1)


if __name__ == "__main__":
    main()
