#!/usr/bin/env python3
"""
research_validator.py - Genesis Architect
Validates that a generated RESEARCH.md is complete and well-formed.
Exits with code 0 if valid, code 1 if issues found.
Requires: Python 3.9+ (uses list[str] type hints)

Usage:
  python scripts/research_validator.py RESEARCH.md
  python scripts/research_validator.py path/to/project/RESEARCH.md
  python scripts/research_validator.py RESEARCH.md --verify-issues   # also HTTP-check GitHub issue URLs
"""

import sys
import re
import urllib.request
import urllib.error

REQUIRED_SECTIONS = [
    "Executive Summary",
    "Search Scope",
    "Analyzed Repositories",
    "Market Landscape",
    "Architecture Decision Rationale",
    "Sources",
]

MIN_REPOS = 5
MIN_SOURCES = 3

GITHUB_ISSUE_RE = re.compile(
    r"https://github\.com/[^/]+/[^/]+/issues/(\d+)"
)


def verify_github_issues(urls: list[str]) -> list[str]:
    """HEAD-check each GitHub issue URL. Returns list of dead URLs."""
    dead = []
    for url in urls:
        try:
            req = urllib.request.Request(url, method="HEAD")
            req.add_header("User-Agent", "genesis-architect-validator/1.0")
            with urllib.request.urlopen(req, timeout=5) as resp:
                if resp.status == 404:
                    dead.append(url)
        except urllib.error.HTTPError as e:
            if e.code == 404:
                dead.append(url)
        except Exception:
            # Network errors are non-fatal - skip rather than false-positive
            pass
    return dead


def validate(path: str, verify_issues: bool = False) -> list[str]:
    """Returns a list of issues. Empty list = valid."""
    issues = []

    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        return [f"File not found: {path}"]

    # Check required sections
    for section in REQUIRED_SECTIONS:
        if section not in content:
            issues.append(f"Missing section: '{section}'")

    # Check repo count in table
    table_rows = re.findall(r"^\|[^|]+\|[^|]+\|[^|]+\|[^|]+\|", content, re.MULTILINE)
    # Subtract header and separator rows
    data_rows = [r for r in table_rows if not re.match(r"^\|\s*[-:]+\s*\|", r)]
    if len(data_rows) < MIN_REPOS:
        issues.append(
            f"Too few repos in table: found {len(data_rows)}, minimum is {MIN_REPOS}"
        )

    # Check for at least MIN_SOURCES links
    links = re.findall(r"""https?://[^\s,)\]>"']+""", content)
    if len(links) < MIN_SOURCES:
        issues.append(f"Too few source links: found {len(links)}, minimum is {MIN_SOURCES}")

    # Check GitHub issue URLs have valid format (owner/repo/issues/number)
    issue_urls = GITHUB_ISSUE_RE.findall(content)
    raw_issue_urls = GITHUB_ISSUE_RE.findall(content)
    all_issue_urls = [m for m in re.findall(r"https://github\.com/[^\s,)\]>\"']+", content)
                     if "/issues/" in m]
    malformed = [u for u in all_issue_urls if not GITHUB_ISSUE_RE.match(u)]
    if malformed:
        issues.append(f"Malformed GitHub issue URLs: {malformed}")

    # Optional: HTTP-verify each issue URL exists (not 404)
    if verify_issues and all_issue_urls:
        valid_urls = [u for u in all_issue_urls if GITHUB_ISSUE_RE.match(u)]
        print(f"  Verifying {len(valid_urls)} GitHub issue URL(s)...", flush=True)
        dead = verify_github_issues(valid_urls)
        for url in dead:
            issues.append(f"GitHub issue URL returns 404 (fabricated?): {url}")

    # Check it was generated by Genesis Architect
    if "Genesis Architect" not in content:
        issues.append("Missing 'Genesis Architect' header - was this generated by the skill?")

    return issues


def main():
    if len(sys.argv) < 2:
        print("Usage: python research_validator.py <path-to-RESEARCH.md> [--verify-issues]")
        sys.exit(1)

    path = sys.argv[1]
    verify_issues = "--verify-issues" in sys.argv

    issues = validate(path, verify_issues=verify_issues)

    if not issues:
        print("RESEARCH.md is valid.")
        sys.exit(0)
    else:
        print(f"RESEARCH.md has {len(issues)} issue(s):")
        for issue in issues:
            print(f"  - {issue}")
        sys.exit(1)


if __name__ == "__main__":
    main()
